# Generated by Django 5.1.2 on 2024-10-20 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HormoneLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hormone_name', models.CharField(max_length=100)),
                ('level', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('date_measured', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HormoneRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hormone_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hormones.hormonelevel')),
            ],
        ),
    ]
