# Generated by Django 5.1.2 on 2024-10-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
