# Generated by Django 5.1.2 on 2024-10-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(default='Untitled Goal', max_length=255),
        ),
    ]
