# Generated by Django 5.1.2 on 2024-10-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_exerciseset_trainingplan_exerciseset_training_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='sets',
            field=models.IntegerField(null=True),
        ),
    ]
