# Generated by Django 5.1.2 on 2024-10-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='calories',
            new_name='calories_per_unit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='carbs',
            new_name='carbs_per_unit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='fat',
            new_name='fat_per_unit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='protein',
            new_name='protein_per_unit',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='total_calories',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(default='grams', max_length=20),
        ),
    ]
