# Generated by Django 5.1.2 on 2024-10-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_calories_per_unit_ingredient_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='total_calories',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('cup', 'cups'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons')], default='grams', max_length=10),
            preserve_default=False,
        ),
    ]
