# Generated by Django 5.1.2 on 2024-10-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_ingredient_created_at_ingredient_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
